cookie:
  expiry_days: 1
  key: 2f3cfd795b2ef1b6a9e5c0d27e84e92837ffdaedc0150f2a6b9f79d88d77afab
  name: cbm_cookie
credentials:
  usernames:
    admin:
      email: admin@multiedro.com.br
      failed_login_attempts: 0
      logged_in: false
      name: Admin
      password: $2b$12$gu/T5o0CSs9W6p/3Jm65jeVFmbkZK90diyyLtaNTgCBH46qTYil7O
      role: admin
    administrativo:
      email: administrativo@cbmlegal.com.br
      first_name: Administrativo
      last_name: null
      logged_in: false
      password: $2b$12$dxSvMUFA7HlAr9gU/RHGyOZMALBxHWdewQ5CjjjcmAHRUTFKj3ycy
      password_hint: Gerado pela Multiedro
      roles: null
    beatriz:
      email: beatriz@cbmlegal.com.br
      first_name: Beatriz
      last_name: null
      logged_in: false
      password: $2b$12$OniX5AqkboQ.ZI9PRmOSEO6hd/wXh5bytdmXNtKvUxgNVF/O3zA2u
      password_hint: Gerado pela Multiedro
      roles: null
    danilo:
      email: danilo@cbmlegal.com.br
      first_name: Danilo
      last_name: Collavini
      logged_in: false
      password: $2b$12$El98CTO7jGlLFwM.qxeBMOy1o4xlUi2UPwSaXz9LhJDHHGAk9xNfy
      password_hint: Gerado pela Multiedro
      roles: null
    filipe:
      email: filipe@cbmlegal.com.br
      first_name: Filipe
      last_name: Collavini
      logged_in: false
      password: $2b$12$E2XY/a.OS0fxF3rRcWMQPei/2TLTjU0DBOtdt.Ygfi9IxD1wxc9he
      password_hint: Gerado pela Multiedro
      roles: null
    flavio:
      email: flavio@cbmlegal.com.br
      first_name: Flavio
      last_name: Collavini
      logged_in: false
      password: $2b$12$IZNbAmkxYy8Uq/NEQg9gwOAhNVqbWluHc0x9RvrrqL64zxU9MNryO
      password_hint: Gerado pela Multiedro
      roles: null
    manoela:
      email: manoela@cbmlegal.com.br
      first_name: Manoela
      last_name: null
      logged_in: false
      password: $2b$12$M7oJaKNKwxt5fylvqaWm.OsCNv5zXVlbfNlF1uQNXb5SUiRcmdLAm
      password_hint: Gerado pela Multiedro
      roles: null
    mariafernanda:
      email: mariafernanda@cbmlegal.com.br
      first_name: Maria
      last_name: Fernanda
      logged_in: false
      password: $2b$12$1ANI4UFdvdP/E/SrObDQNuUp0RqZ4Cww0peAXvlr2ogL.13nxfLFi
      password_hint: Gerado pela Multiedro
      roles: null
    mariavictoria:
      email: mariavictoria@cbmlegal.com.br
      first_name: Maria
      last_name: Victoria
      logged_in: false
      password: $2b$12$zO/4FyPram/A7cYdNlAtmejssbbhUWS1vKJpnTGMtHNDBQJAOpdB.
      password_hint: Gerado pela Multiedro
      roles: null
    nathalia:
      email: nathalia@cbmlegal.com.br
      first_name: Nathalia
      last_name: null
      logged_in: false
      password: $2b$12$ENVTNy3x/HDQCyPoekV.5u7TjSsLRebyuaTvDgQVZtImuu3KnRx.e
      password_hint: Gerado pela Multiedro
      roles: null
    stefano:
      email: stefano@cbmlegal.com.br
      first_name: Stefano
      last_name: Collavini
      logged_in: false
      password: $2b$12$1THBXEpdmOi6FMzBc2DRv.kXDZM9qzUwmrCRcgEbbrrfrZYfsSsWi
      password_hint: Gerado pela Multiedro
      roles: null
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
